### PR TITLE
Mark this module as @safe pure and nothrow

### PR DESCRIPTION
**Pull request by JesseKPhillips**
This is built off Pull #1 and marks all functions with the three listed properties.

### CODE REVIEW

**Comment by extrawurst** [comment]
i dont want to drop full gdc support because of that. can you make it work with gdc ?

**Comment by JesseKPhillips** [comment]
@Extrawurst, I've made changes that should be working with GDC (older DMD versions) I'm not sure why CI is failing, local tests with GDC 4.9 are passing.

**Comment by extrawurst** [comment]
Thanks the helper methods are the problem, they use dup, still

**Comment by extrawurst** [comment]
Whatever I ditched a couple of old compilers now

**Comment by JesseKPhillips** [comment]
@Extrawurst, can add a version tag for these changes so dub can pick them up?

**Comment by extrawurst** [comment]
done: https://github.com/Extrawurst/xtea-d/releases/tag/v0.2.0

**Pull request merged**
